### PR TITLE
TOMEE-3846 fixed tomee flavors comparison page

### PR DESCRIPTION
**Pull request by sultan**
fixed consistence between "flavors comparison page in website" versus "actual jars being present in releases"

question to reviewer : Is it intended to have Plus not containing Eclipselink while Plume not containing batchee in recent releases ?
if not : need to update poms and postpone this PR.
if yes : need to update website, visual for pushed version (changed parts) below :

image
[ ... mulitple unchanged lines here ]
image

listening to your suggestions for the synthetic table (my students would appreciate this synthesis)

here is an alternative visual :

image
[ ... mulitple unchanged lines here ]
image

https://issues.apache.org/jira/browse/TOMEE-3846

### CODE REVIEW

**Comment by rzo1** [comment]
@sultan I saw your comments in TOMEE-3846. Would you mind dropping an e-mail at dev@tomee.apache.org to discuss / adress your questions raised in TOMEE-3846? Typically, this will get more attentation than the JIRA / GitHub PR mails (might get overseen due to heavy automated mail traffic).

**Comment by sultan** [comment]
dropped a mail to dev@tomee.apache.org

**Comment by rzo1** [comment]
> dropped a mail to [dev@tomee.apache.org](mailto:dev@tomee.apache.org)

Thanks, @sultan

**Comment by rzo1** [comment]
> dropped a mail to dev@tomee.apache.org 

Didn't come through? At least, I couldn't see it in the archive.

Might be a helpful resource regarding the differentiation between flavours:
 https://www.tomitribe.com/blog/tomee-webprofile-vs-tomee-microprofile-vs-tomee-vs-tomee-plume/

Might be a reference how it was thought initially.

**Comment by sultan** [comment]
the link you provided is the same i used to make suggestions and edit the page. that comforts me in the quality of this source :-)
thanks for letting me know the mail did not pass trough. i will send another one.

**Comment by dblevins** [comment]
The list will send posts from non-subscribers to moderation/spam.

Send a note to dev-subscribe @ tomee.apache.org, respond to the confirmation email then go ahead and post again.

**Comment by sultan** [comment]
Thanks for your mods and merge @dblevins !
As pointed out by John Waterwood on twitter, i had to mod the synthesis table to make Authentication and Authorization more readable.

my branch is ready for a new PR if needed

image

image

**Pull request merged**
