### PR TITLE
Update Links in Commercial Support Page

### PR DESCRIPTION
**Pull request by gerdogdu**
**What this PR Does?**
1. The commercial support link in page [https://tomee.apache.org/security/support.html](https://tomee.apache.org/security/support.html) is broken. This PR fixes it.
2. There is href link in ManageCat text in commercial support as Tomitribe does. This PR improves this.

Hope to merge this PR as soon as possible and publish into website.

Regards.
Gurkan

### CODE REVIEW

**Comment by gerdogdu** [comment]
@jeanouii Can you please look and merge this?

**Review by rzo1 — APPROVED** [review]
lgtm

**Comment by gerdogdu** [comment]
This is a very small change. Could you please merge this into the upstream and update the web site? @rzo1 @jeanouii

**Comment by rzo1** [comment]
I manually triggered the CI to publish the change to avoid waiting 12h again. Thanks for fixing the broken navigation link!

**Comment by gerdogdu** [comment]
@rzo1 Thank you very much.

**Comment by rzo1** [comment]
@gerdogdu it is deployed now.

**Pull request merged**
