### PR TITLE
TOMEE-3981 update javadoc to reflect updates on Jakarta EE

### PR DESCRIPTION
**Pull request by sultan**
Javadoc is missing (java|jakarta).validation package and others

actions taken :

added missing api docs : 
* activation
* authentication
* authorization
* batch
* cdi
* deployment
* expression-language
* faces
* mail
* management
* mvc
* rpc
* validation

new versions : 
* annotations 2.1.1
* enterprise-beans 4.0.1
* faces 4.0.1
* jsonp 2.0.2
* jsonp 2.1.1
* transactions 2.0.1

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
+1, Thank you @sultan !

**Comment by sultan** [comment]
the "Faces" project did not have any .java file, and did not generate any javadoc.
so i took the "Faces API" from the api part of Mojarra.

**Comment by sultan** [comment]
Jakarta EE 10 is taking more time than expected for a release, maybe we can merge this PR and make a smaller one when the few last dependencies (ejb, inject, transaction, validation, mail, jws) are released.

**Comment by sultan** [comment]
added missing doc for mvc-api

**Comment by sultan** [comment]
added missing doc for deployment-api

**Comment by sultan** [comment]
added batch 2.1.1 and concurrency 3.0.1

**Comment by rzo1** [comment]
@sultan Do you think we can go ahead with this PR?

**Comment by dblevins** [comment]
Really great to see the missing specs added and the new repo locations.  I can't believe we missed CDI! :)

Note, Mvc is not part of any Jakarta EE release, so we should yank it.  We should also probably not use "master" for any of the Jakarta EE 10 repos.   The Jakarta EE Platform isn't final quite yet, but here's a draft from the first vote attempt this month.  Versions are listed on this page:

 - https://deploy-preview-498--jakartaee-specifications.netlify.app/specifications/platform/10/jakarta-platform-spec-10.0.html#relateddocs

**Comment by sultan** [comment]
* Jakarta MVC is indeed released outside the full platform poms. commented out to prevent they come back again.
* Jakarta EE 10 does not upgrade for the features i waited, namely : ejb, injection, rest, transactions, validation, jws, metadata. EE 10 and EE 9.1 share the same versions for these features.
* no more master references for jakarta ee, versions taking account of html pages provided by @dblevins 
* commented out microprofile 6.0 until official announcements

Ready for merge.

**Comment by sultan** [comment]
looks like EE 10 upgrades rest-api to v3.1.0, according to this pom : https://github.com/eclipse-ee4j/jakartaee-api/blob/master/pom.xml and to this page : https://jakarta.ee/specifications/restful-ws/

**Comment by sultan** [comment]
Jakarta EE 10 apis and jars are released (non rc) !

things to note : 
* new flavor : Jakarta EE Core Profile
* new api : jakarta.enterprise.lang-model v4.0.1
* Concurrency jakarta.enterprise.concurrent-api : now included in Web Profile
* JWS Metadata : now part of another spec

i'll try to help on TomEE v10 (?) once the branch is created.

**Comment by sultan** [comment]
Updated concurrency api to 3.0.2

**Comment by sultan** [comment]
is my PR ok for you @dblevins ?

Thank you for your time :)

**Comment by sultan** [comment]
MP Config 3.0.2
MP FT 4.0.1

**Comment by rzo1** [comment]
Thanks @sultan

**Pull request merged**
